### ISSUE TITLE
Security time ignored

### ISSUE THREAD

**Issue by Yenthe666** [Yenthe666/rental#2]
Steps:
1. Create a rental product and set a security time of 48h:
![image](https://user-images.githubusercontent.com/6352350/128671436-cfcb700f-866f-483e-8208-64cbcdfcd1a6.png)

2. Go to the website and try to rent it tommorow:
![image](https://user-images.githubusercontent.com/6352350/128671468-1f57d8e7-6472-4bb7-ba28-71afbb41a893.png)

Issue:
This shouldn't be allowed as tommorow, the 10'th of august, is within that 48h period?

**Comment by Yenthe666** [comment]
@holdenrehg can you check?

**Comment by holdenrehg** [comment]
I think maybe just a misunderstanding in requirements on my end.

The **current behavior** now is: security time is used to pad the start date when checking for conflicting orders. For example, if the Meeting Room is scheduled for September 5th then a new order cannot be put in on the 4th. I thought the ideas was to give security time for customers to return product or something (with physical items).

So instead, should the expected behavior just be to pad the current time/order time + padding?

**Comment by Yenthe666** [comment]
@holdenrehg let's do it as follows:
If the security lead time is set to 48h and today is 16/08/2021 then you cannot rent it before 18/08/2021. So if a security lead time is set you cannot book the product in any way before this grace period.

**Comment by holdenrehg** [comment]
Got it @Yenthe666 :+1: take a look.

**Comment by Yenthe666** [comment]
Customer is giving it some testing :) Will get back to you soon.

**Comment by Yenthe666** [comment]
Closing this for now, introduced it into the 14.0 at https://github.com/Yenthe666/rental/commit/609fc4c861ec51ce49f24a946209f21ea7dc7d67

**Comment by Yenthe666** [comment]
@holdenrehg I found at least one issue on short term blockings. It looks fine on 24h or more 🤔 
A sample configuration done on 29/08/2021 at 14:00 for a product. We set a delay of 4h:
![image](https://user-images.githubusercontent.com/6352350/131249638-bc64ce62-1b60-4507-a267-9ea6cfda3eb7.png)

Now in the UI try to book it:
![image](https://user-images.githubusercontent.com/6352350/131249674-6f6c596a-44db-4723-8e92-994cccca74c4.png)

These slots should not be enabled as this is within the safety margin
